Support script file extensions and non-executables
Allow both scripts to be renamed to an arbitrary extension such as *.sh,
without a need to modify the contents of the scripts for that.

Also, allow both scripts to be plain text files without requirement for
executable permissions, which are invoked directly by passing the script
name as an argument to the "sh" command.

Together, this will allow both scripts to be invoked directly from a
FAT-filesystem which does not support the concept of an "executable"-
permission (depending on the mount options).

Supporting to rename the files to an arbitrary file extension (such as
".sh") allows to register a custom interpreter for Bourne Shell scripts
with the Microsoft Windows registry, which does not support the UNIX
"shebang"-mechanism at all.

diff --git a/gbkdf b/gbkdf
--- a/gbkdf
+++ b/gbkdf
@@ -19,6 +19,12 @@
 # resides on a securely encrypted disk. Likewise, if the system has been
 # configured to use swap space, this swap space should be encrypted as well in
 # order to avoid leaking sensitive data there.
+#
+# gbkdf version 15.280
+#
+# (c) 2015 by Guenther Brunthaler.
+# This script is free software.
+# Distribution is permitted under the terms of the GPLv3.
 
 set -e
 # Set defaults.
@@ -57,12 +63,16 @@ fi
 
 
 cleanup() {
+	local rc=$?
 	test -z "$DEBUG" && test -n "$T" && rm -r -- "$T"
-	test -n "$OK" || echo "Failed!" >& 2
+	test $rc = 0 || {
+		echo "${0##*/} failed!"
+		echo "See the comments at the beginning of that script for" \
+			"usage instructions."
+	} >& 2
 }
 
 
-OK=
 T=
 trap cleanup 0
 
@@ -154,4 +164,3 @@ do
 	done
 	cat "$data" || break
 done
-OK=Y
diff --git a/gbosslcrypt b/gbosslcrypt
--- a/gbosslcrypt
+++ b/gbosslcrypt
@@ -1,6 +1,7 @@
 #! /bin/sh
-# Encrypt (-e) or decrypt (-d) stdin to stdout. Only argument: The pathame of
-# a file containing the password in current locale encoding in the first line.
+# Encrypt (-e) or decrypt (-d) stdin to stdout. The only argument: The pathame
+# of a file containing the password in current locale encoding in the first
+# line.
 #
 # This script always uses /tmp (or the directory specified with the -t option)
 # to store temporary working files containing sensitive data (mlock-like
@@ -9,6 +10,17 @@
 # resides on a securely encrypted disk. Likewise, if the system has been
 # configured to use swap space, this swap space should be encrypted as well in
 # order to avoid leaking sensitive data there.
+#
+# Data encrypted by this script will be binary output. The recommended file
+# extension is ".gbo". It text-based output is required, conversion into
+# base-64 or basE91-formats is recommended, and the file extensions could be
+# something like "_gbo.b64" and "_gbo.b91", respecively.
+#
+# gbosslcrypt version 15.280
+#
+# (c) 2015 by Guenther Brunthaler.
+# This script is free software.
+# Distribution is permitted under the terms of the GPLv3.
 
 set -e
 saltbits=512
@@ -18,12 +30,16 @@ encryption_order=$encryption_order' rc4#8$128'
 
 
 cleanup() {
+	local rc=$?
 	test -n "$T" && rm -r -- "$T"
-	test -n "$OK" || echo "Failed!" >& 2
+	test $rc = 0 || {
+		echo "${0##*/} failed!"
+		echo "See the comments at the beginning of that script for" \
+			"usage instructions."
+	} >& 2
 }
 
 
-OK=
 T=
 trap cleanup 0
 
@@ -33,8 +49,9 @@ then
 	script=`which $script`
 	test -f "$script"
 fi
-pbkdf=`dirname "$script"`/$pbkdf
-test -x "$pbkdf"
+sxt=${0##*/}; sxt=${sxt#${sxt%.*}}
+pbkdf=`dirname -- "$script"`/$pbkdf$sxt
+test -f "$pbkdf"
 
 mode=
 unset TMPDIR
@@ -80,7 +97,7 @@ parse_algo() {
 
 set -- $encryption_order
 # Generate keys.
-"$pbkdf" -t"$TMPDIR" $passthrough_flags "$salt" "$psw" | {
+sh "$pbkdf" -t"$TMPDIR" $passthrough_flags "$salt" "$psw" | {
 	lastbbits=8
 	for algo
 	do
@@ -134,5 +151,3 @@ crypt() {
 }
 
 crypt "$@"
-
-OK=Y
